title: ma website
#baseURL: https://vno-hugo.netlify.app/
theme: Vno-Hugo
defaultContentLanguage: zh-cn
languages:
  en-us:
    languageName: English(United States)
    weight: 10
  zh-cn:
    languageName: 简体中文（中国大陆）
    paginate: 10
    paginatePath: page
    weight: 20
outputs:
  home:
    - HTML
    - RSS
menu:
  main:
    - identifier: Learning materials
      name: Learning materials
      url: /content/newpost/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
taxonomies:
  tag: tags
params:
  author: onevcat
  blogButton:
    description: Visit blog
    title: Blog
  comment:
    disqus: vno-hugo
    duoshuo: ''
    gitalk:
      ID: ''
      owner: ''
      repo: ''
      secret: ''
  copyright:
    license: CC BY-NC-SA 4.0
    license_link: http://creativecommons.org/licenses/by-nc-sa/4.0/
  coverColor: red
  description: 衣带渐宽终不悔，为伊消得人憔悴
  ga:
    ID: your_ga_id
    host: your_host
  social:
    github: onevcat
    gplus: '107108267983477358170'
    linkedin: example
    mail: onev@onevcat.com
    twitter: onevcat
    weibo: onevcat
  subtitle: A blog-website for ma 
  welcomeMessage: Oh What a World
permalinks:
  posts: /:year/:month/:title/
